# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('whiteIp', models.GenericIPAddressField()),
                ('lastCheckedTime', models.BigIntegerField(default=0)),
                ('numberOfBadChecks', models.IntegerField(default=0)),
                ('badProxy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['whiteIp'], name='core_proxy_whiteIp_7c85c0_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['badProxy'], name='core_proxy_badProx_2035a8_idx'),
        ),
    ]
