# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='whiteIp',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
